# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches:
    - '**'
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Python Blacken
        # You may pin to the exact commit or the version.
        # uses: piotrpawlaczek/python-blacken@00da49d5262ea8408aa006873de629fef9fc9dd1
      uses: piotrpawlaczek/python-blacken@v20.8b1
      with:
        # File or directory to run black on.
        path: . # optional, default is .
        # The number of characters allowed per line.
        line-length: 88 # optional, default is 81
    - name: Python Markdown Documentation
      # You may pin to the exact commit or the version.
      # uses: jbheard/markdown-docs@c97b542c3d24257d97d55179445e339251618220
      uses: jbheard/markdown-docs@v0.1
      with:
        # Path to the source folder containing python code
        src_path: . # optional, default is .
        # Directory to create markdown documents in
        dst_path: docs # optional, default is docs
